baseurl             = "https://uzluisf.github.io/"
title               = "uzluisf"
theme               = "hugo-dpdpb"
languageCode        = "en-US"

contentdir          = "content"
publishdir          = "public"
layoutdir           = "layouts"

builddrafts         = false
canonifyurls        = true
pygmentsuseclasses  = true
pluralizelisttitles = false

[permalinks]
blog  = "blog/:slug/"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "About"
weight                 = -110
identifier             = "about"
url                    = "/about/"

[params]
paginate               = 10
include_rss            = true                          # include RSS <link> tag in <head> and show RSS icon
latestpostscount       = 5                             # how many posts to display on the home page
i18n_flags             = false                         # whether to display small country flags for available translations
author                 = "Luis Uceta"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Don't panic"

avatar                 = "img/profile.png"             # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
faviconfile            = "img/leaf.ico"

lang                   = "en"
email                  = ""
github                 = "//github.com/uzluisf"
twitter                = "//twitter.com/uzluisf"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
selfintro              = ""                            # appears in the site header when set to a non-empty string

highlightjs            = true
